// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

type Client struct {
	ID          int64
	Firstname   string
	Lastname    string
	Fathersname string
	Title       string
	Ipn         string
	Address     string
	Account     string
	Phone       string
}

type DocTransaction struct {
	ID         int64
	Documentid int64
	Amount     string
}

type Document struct {
	ID           int64
	Executorid   int64
	Contractorid int64
	Date         string
	Title        string
}
