// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';

export function CreateDocument(arg1:api.CreateDocumentParams):Promise<number>;

export function CreateTransaction(arg1:api.CreateDocTransaction):Promise<api.DocTransaction>;

export function DeleteClient(arg1:number):Promise<void>;

export function DeleteDocument(arg1:number):Promise<void>;

export function DeleteTransaction(arg1:number):Promise<void>;

export function GetAllClients():Promise<Array<api.Client>>;

export function GetClient(arg1:number):Promise<api.Client>;

export function GetDocumentByID(arg1:number):Promise<api.Document>;

export function GetDocuments():Promise<Array<api.Document>>;

export function GetTransactionsByDoc(arg1:number):Promise<Array<api.DocTransaction>>;

export function NewClient(arg1:api.CreateClientParams):Promise<api.Client>;

export function UpdateClient(arg1:api.UpdateClientByIDParams):Promise<void>;
