// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDocument(arg1) {
  return window['go']['api']['API']['CreateDocument'](arg1);
}

export function CreateTransaction(arg1) {
  return window['go']['api']['API']['CreateTransaction'](arg1);
}

export function DeleteClient(arg1) {
  return window['go']['api']['API']['DeleteClient'](arg1);
}

export function DeleteDocument(arg1) {
  return window['go']['api']['API']['DeleteDocument'](arg1);
}

export function DeleteTransaction(arg1) {
  return window['go']['api']['API']['DeleteTransaction'](arg1);
}

export function GetAllClients() {
  return window['go']['api']['API']['GetAllClients']();
}

export function GetClient(arg1) {
  return window['go']['api']['API']['GetClient'](arg1);
}

export function GetDocumentByID(arg1) {
  return window['go']['api']['API']['GetDocumentByID'](arg1);
}

export function GetDocuments() {
  return window['go']['api']['API']['GetDocuments']();
}

export function GetTransactionsByDoc(arg1) {
  return window['go']['api']['API']['GetTransactionsByDoc'](arg1);
}

export function NewClient(arg1) {
  return window['go']['api']['API']['NewClient'](arg1);
}

export function UpdateClient(arg1) {
  return window['go']['api']['API']['UpdateClient'](arg1);
}
